name: Build Patched Repository

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 0 */3 * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout current repository
      uses: actions/checkout@v4
      with:
        sparse-checkout: |
          *.patch
        sparse-checkout-cone-mode: false
    
    - name: Setup Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest
    
    - name: Clone target repository
      run: |
        git clone https://github.com/revenge-mod/revenge-bundle-next.git revenge
        cd revenge
    
    - name: Apply patches
      run: |
        cd revenge
        git apply ../*.patch
    
    - name: Install dependencies
      run: |
        cd revenge
        bun install
    
    - name: Build project
      run: |
        cd revenge
        bun run build

    - name: Setup Pages
      uses: actions/configure-pages@v5

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: revenge/dist

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4